"""followers

Revision ID: e383cf98fc0f
Revises: beaf3b364df3
Create Date: 2020-11-06 19:31:23.027276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e383cf98fc0f"
down_revision = "beaf3b364df3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers",
        sa.Column("follower_id", sa.Integer(), nullable=True),
        sa.Column("followed_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["followed_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("followers")
    # ### end Alembic commands ###
